# Generated by Django 3.2.4 on 2021-06-26 12:48

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210624_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=page.models.save_lesson_files, verbose_name='Media'),
        ),
    ]
