# Generated by Django 3.2.4 on 2021-06-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
