# Generated by Django 3.2.4 on 2021-06-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210624_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='classroom.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='classroom.classes'),
        ),
    ]
