# Generated by Django 3.2.4 on 2021-06-28 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0011_auto_20210627_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='enrolled',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
