# Generated by Django 3.2.4 on 2021-06-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_classes_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
    ]
