# Generated by Django 3.0.6 on 2021-06-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_auto_20210606_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
