# Generated by Django 3.2.4 on 2021-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_statut',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='6eme', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='student', max_length=10),
        ),
    ]
